# Generated by Django 3.2 on 2022-03-01 15:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Titre du projet')),
                ('project_duration', models.IntegerField(default=0, verbose_name='Durée Estimée')),
                ('time_allocated', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'The minimum Value required is 1'), django.core.validators.MaxValueValidator(10, 'The maximum Value required is 10')], verbose_name='Temps Alloué')),
                ('needs', models.TextField(max_length=250, verbose_name='Besoins')),
                ('desciption', models.TextField(max_length=250)),
                ('isValid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10, verbose_name='First Name')),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hub.user')),
            ],
            bases=('Hub.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Hub.user')),
            ],
            bases=('Hub.user',),
        ),
        migrations.CreateModel(
            name='MembershipInProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allocated', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.projet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hub.student')),
            ],
            options={
                'verbose_name_plural': 'MemberShip',
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_Owner', to='Hub.student'),
        ),
        migrations.AddField(
            model_name='projet',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='Les_membres', through='Hub.MembershipInProjects', to='Hub.Student'),
        ),
        migrations.AddField(
            model_name='projet',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_Coach', to='Hub.coach'),
        ),
    ]
